// GrainIQ PDF report generation. Runs entirely client-side (jsPDF) — the
// micrograph is passed in as a data URL already rendered in the browser, so the
// image still never leaves the machine, matching the privacy promise.
//
// buildReportDoc() returns a jsPDF document (pure, no I/O — unit-testable in
// Node); downloadReportPdf() builds it and triggers the browser download.
import { jsPDF } from 'jspdf'

// Brand palette, tuned for legibility on white (print) rather than the app's
// dark theme. RGB triples.
const INK = [15, 23, 42] // slate-900
const BODY = [51, 65, 85] // slate-700
const MUTED = [100, 116, 139] // slate-500
const HAIR = [226, 232, 240] // slate-200 — hairline rules
const TEAL = [13, 148, 136] // teal-600 — accents
const TEAL_DEEP = [15, 118, 110] // teal-700 — headings
const TEAL_TINT = [240, 253, 250] // teal-50 — hero panel
const AMBER_TEXT = [146, 64, 14] // amber-800
const AMBER_BG = [255, 251, 235] // amber-50
const AMBER_BORDER = [253, 230, 138] // amber-300

// Overlay colours, matching the canvas annotation in Dashboard.jsx.
const LEGEND = [
  { rgb: [45, 212, 191], label: 'Test lines' },
  { rgb: [251, 113, 133], label: 'Intercept ticks' },
  { rgb: [250, 204, 21], label: 'Detected boundaries' },
]

const PAGE_W = 210
const PAGE_H = 297
const MARGIN = 16
const CONTENT_W = PAGE_W - 2 * MARGIN

const DISCLAIMER =
  'Results generated by GrainIQ are indicative and intended to support analysis. They do not ' +
  'constitute certified measurement under ASTM E112 or ISO 643 and should not be used as the ' +
  'sole basis for material certification without independent verification.'

const METHOD_LABELS = {
  watershed: 'Watershed segmentation',
  canny: 'Canny edge detection',
  threshold: 'Dark threshold (legacy Otsu)',
}
const ORIENTATION_LABELS = {
  both: 'Horizontal + vertical',
  horizontal: 'Horizontal only',
  vertical: 'Vertical only',
}

function formatDateTime(date) {
  return date.toLocaleString('en-GB', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
}

// Method-specific detail rows for the parameters panel.
function methodDetailRows(method, detail) {
  if (!detail) return []
  if (method === 'watershed') {
    const rows = []
    if (detail.grains !== undefined) rows.push(['Grains segmented', String(detail.grains)])
    if (detail.threshold !== undefined)
      rows.push(['Boundary threshold', `${detail.threshold} (${detail.polarity})`])
    return rows
  }
  if (method === 'threshold' && detail.threshold !== undefined) {
    return [['Otsu threshold', String(detail.threshold)]]
  }
  if (method === 'canny' && detail.highThreshold !== undefined) {
    return [['Edge thresholds (low-high)', `${detail.lowThreshold} - ${detail.highThreshold}`]]
  }
  return []
}

/**
 * Build the report as a jsPDF document. Pure: no download, no DOM beyond jsPDF.
 *
 * @param {object} d report data (see Dashboard handleExport).
 * @returns {jsPDF}
 */
export function buildReportDoc(d) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', compress: true })
  const now = d.now ?? new Date()
  let y = 0

  // --- Header -------------------------------------------------------------
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.setTextColor(...INK)
  doc.text('Grain', MARGIN, 19)
  const grainW = doc.getTextWidth('Grain')
  doc.setTextColor(...TEAL)
  doc.text('IQ', MARGIN + grainW, 19)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(...MUTED)
  doc.text('Mean Linear Intercept Grain Size Report', MARGIN, 25)

  doc.setFontSize(9)
  doc.setTextColor(...BODY)
  doc.text(`Generated  ${formatDateTime(now)}`, PAGE_W - MARGIN, 15, { align: 'right' })
  if (d.analyst) doc.text(`Analyst  ${d.analyst}`, PAGE_W - MARGIN, 20, { align: 'right' })
  doc.text('Standard  ASTM E112', PAGE_W - MARGIN, 25, { align: 'right' })

  doc.setDrawColor(...TEAL)
  doc.setLineWidth(0.6)
  doc.line(MARGIN, 29, PAGE_W - MARGIN, 29)
  y = 37

  // --- Hero stats ---------------------------------------------------------
  const heroH = 22
  doc.setFillColor(...TEAL_TINT)
  doc.roundedRect(MARGIN, y, CONTENT_W, heroH, 2, 2, 'F')
  const heroes = [
    { label: 'Mean linear intercept', value: d.mliMicrons != null ? `${d.mliMicrons.toFixed(2)} µm` : '—', accent: true },
    { label: 'ASTM grain size (G)', value: d.grainNumber != null ? d.grainNumber.toFixed(1) : '—', accent: true },
    { label: 'Intercepts counted', value: String(d.totalIntercepts ?? '—'), accent: false },
  ]
  const heroCellW = CONTENT_W / heroes.length
  heroes.forEach((h, i) => {
    const cx = MARGIN + i * heroCellW + 5
    if (i > 0) {
      doc.setDrawColor(...HAIR)
      doc.setLineWidth(0.2)
      doc.line(MARGIN + i * heroCellW, y + 4, MARGIN + i * heroCellW, y + heroH - 4)
    }
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7.5)
    doc.setTextColor(...MUTED)
    doc.text(h.label.toUpperCase(), cx, y + 7)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(17)
    doc.setTextColor(...(h.accent ? TEAL_DEEP : INK))
    doc.text(h.value, cx, y + 16)
  })
  y += heroH + 8

  // Reusable section heading with an underline rule spanning `w`.
  const heading = (label, x, w, yy) => {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(...TEAL_DEEP)
    doc.text(label.toUpperCase(), x, yy)
    doc.setDrawColor(...HAIR)
    doc.setLineWidth(0.2)
    doc.line(x, yy + 1.5, x + w, yy + 1.5)
  }

  // --- Annotated micrograph ----------------------------------------------
  heading('Annotated micrograph', MARGIN, CONTENT_W, y)
  y += 6

  const aspect = d.imageWidth && d.imageHeight ? d.imageWidth / d.imageHeight : 4 / 3
  const maxImgH = 96
  let imgW = CONTENT_W
  let imgH = imgW / aspect
  if (imgH > maxImgH) {
    imgH = maxImgH
    imgW = imgH * aspect
  }
  const imgX = MARGIN + (CONTENT_W - imgW) / 2
  if (d.imageDataUrl) doc.addImage(d.imageDataUrl, 'PNG', imgX, y, imgW, imgH)
  doc.setDrawColor(...HAIR)
  doc.setLineWidth(0.3)
  doc.rect(imgX, y, imgW, imgH)
  y += imgH + 5

  // Legend swatches
  let lx = MARGIN
  doc.setFontSize(8)
  for (const item of LEGEND) {
    doc.setFillColor(...item.rgb)
    doc.rect(lx, y - 2.6, 3, 3, 'F')
    doc.setTextColor(...MUTED)
    doc.text(item.label, lx + 4.2, y)
    lx += 4.2 + doc.getTextWidth(item.label) + 7
  }
  if (d.scaleSource === 'Scale bar calibration') {
    doc.setFillColor(...HAIR)
    doc.rect(lx, y - 2.6, 3, 3, 'F')
    doc.setTextColor(...MUTED)
    doc.text('Scale bar', lx + 4.2, y)
  }
  y += 8

  // --- Two detail panels --------------------------------------------------
  const panel = (title, items, x, w, startY) => {
    heading(title, x, w, startY)
    let yy = startY + 6
    doc.setFontSize(9)
    for (const [label, value] of items) {
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...MUTED)
      doc.text(label, x, yy)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...BODY)
      doc.text(String(value), x + w, yy, { align: 'right' })
      yy += 5.6
    }
    return yy
  }

  const interceptRows = []
  if (d.orientation === 'both' && d.directions) {
    interceptRows.push(['Intercepts (horizontal)', String(d.directions.horizontal.intercepts)])
    interceptRows.push(['Intercepts (vertical)', String(d.directions.vertical.intercepts)])
  }
  interceptRows.push(['Intercepts (total)', String(d.totalIntercepts ?? '—')])
  // When the analyst hand-corrected intercepts, show the automated baseline and
  // the edits so the report is transparent about what was adjusted.
  if (d.manualEdits > 0) {
    interceptRows.push(['Automated count', String(d.automatedIntercepts ?? '—')])
    interceptRows.push(['Manual corrections', `+${d.manualAdded ?? 0} / -${d.manualRemoved ?? 0}`])
  }

  const resultsItems = [
    ['Mean linear intercept', d.mliMicrons != null ? `${d.mliMicrons.toFixed(2)} µm` : '—'],
    ['ASTM grain size (G)', d.grainNumber != null ? d.grainNumber.toFixed(1) : '—'],
    ...interceptRows,
    ['Total test-line length', `${(d.totalLengthMm ?? 0).toFixed(2)} mm`],
  ]

  const calibrationDetail = d.calibrated
    ? `${d.calibrated.realMicrons} µm over ${d.calibrated.lengthPx.toFixed(1)} px`
    : `Magnification ${d.magnification}x (estimate)`
  const paramItems = [
    ['Detection method', METHOD_LABELS[d.method] ?? d.method],
    ['Test line orientation', ORIENTATION_LABELS[d.orientation] ?? d.orientation],
    [d.orientation === 'both' ? 'Lines per direction' : 'Number of lines', String(d.numLines)],
    ['Detection sensitivity', String(d.sensitivity)],
    ...methodDetailRows(d.method, d.detail),
    ['Scale source', d.scaleSource],
    ['Scale', `${d.scale.toFixed(4)} µm/px`],
    ['Calibration', calibrationDetail],
    ['Source image', d.fileName ?? '—'],
    ['Analysis resolution', `${d.imageWidth} x ${d.imageHeight} px`],
  ]

  const colW = (CONTENT_W - 8) / 2
  const leftEnd = panel('Measurement results', resultsItems, MARGIN, colW, y)
  const rightEnd = panel('Analysis parameters & calibration', paramItems, MARGIN + colW + 8, colW, y)
  y = Math.max(leftEnd, rightEnd) + 4

  // --- Disclaimer ---------------------------------------------------------
  doc.setFontSize(8)
  const discLines = doc.splitTextToSize(DISCLAIMER, CONTENT_W - 8)
  const discH = 7 + discLines.length * 3.6
  if (y + discH > PAGE_H - 18) {
    doc.addPage()
    y = MARGIN
  }
  doc.setFillColor(...AMBER_BG)
  doc.setDrawColor(...AMBER_BORDER)
  doc.setLineWidth(0.3)
  doc.roundedRect(MARGIN, y, CONTENT_W, discH, 1.5, 1.5, 'FD')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(7.5)
  doc.setTextColor(...AMBER_TEXT)
  doc.text('DISCLAIMER', MARGIN + 4, y + 5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...BODY)
  doc.text(discLines, MARGIN + 4, y + 9.5)

  // --- Footer + free-tier watermark on every page -------------------------
  const pages = doc.getNumberOfPages()
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p)

    if (!d.isPro) {
      try {
        doc.saveGraphicsState()
        doc.setGState(doc.GState({ opacity: 0.07 }))
        doc.setFont('helvetica', 'bold')
        doc.setFontSize(64)
        doc.setTextColor(...TEAL)
        doc.text('GrainIQ', PAGE_W / 2, PAGE_H / 2 + 20, { align: 'center', angle: 30 })
        doc.restoreGraphicsState()
      } catch {
        // GState unsupported in this build — skip the watermark, never fail export.
      }
    }

    doc.setDrawColor(...HAIR)
    doc.setLineWidth(0.2)
    doc.line(MARGIN, PAGE_H - 12, PAGE_W - MARGIN, PAGE_H - 12)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7.5)
    doc.setTextColor(...MUTED)
    doc.text('Generated by GrainIQ  ·  grainiq.co.uk', MARGIN, PAGE_H - 8)
    if (!d.isPro) {
      doc.text('Free plan — upgrade to Pro for unwatermarked reports', PAGE_W / 2, PAGE_H - 8, {
        align: 'center',
      })
    }
    doc.text(`Page ${p} of ${pages}`, PAGE_W - MARGIN, PAGE_H - 8, { align: 'right' })
  }

  return doc
}

// Build the report and trigger a browser download.
export function downloadReportPdf(d) {
  const doc = buildReportDoc(d)
  const base = (d.fileName || 'micrograph')
    .replace(/\.[^.]+$/, '')
    .replace(/[^a-z0-9_-]+/gi, '_')
    .slice(0, 40)
  const datePart = (d.now ?? new Date()).toISOString().slice(0, 10)
  doc.save(`GrainIQ_report_${base}_${datePart}.pdf`)
}
